# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-30 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0003_userprofile_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pay',
            field=models.CharField(default='', max_length=128, verbose_name='支付密码'),
        ),
    ]
